import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#274775",
        "surface-dim": "#dad9de",
        "on-tertiary-fixed": "#2d1600",
        "on-background": "#1a1c1f",
        "tertiary-fixed-dim": "#f9ba7e",
        "on-tertiary-container": "#d49960",
        "secondary-fixed": "#dfe3e7",
        "background": "#faf9fd",
        "inverse-on-surface": "#f1f0f5",
        "on-error": "#ffffff",
        "outline": "#747780",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e8e7ec",
        "surface-bright": "#faf9fd",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#171c1f",
        "surface-tint": "#405f8e",
        "surface": "#faf9fd",
        "secondary-container": "#dce0e4",
        "utility-gray": "#64748B",
        "tertiary": "#3a1e00",
        "secondary-fixed-dim": "#c3c7cb",
        "primary-fixed": "#d5e3ff",
        "on-primary-fixed": "#001b3c",
        "on-primary-container": "#88a6da",
        "on-secondary-fixed-variant": "#43474b",
        "surface-variant": "#e3e2e6",
        "primary-fixed-dim": "#a9c8fd",
        "surface-container": "#eeedf2",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e2e6",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#593100",
        "tertiary-fixed": "#ffdcbf",
        "on-secondary": "#ffffff",
        "surface-ice": "#F9FAFB",
        "primary": "#00254e",
        "on-tertiary-fixed-variant": "#673d0a",
        "primary-container": "#193b68",
        "secondary": "#5a5f62",
        "outline-variant": "#c3c6d0",
        "on-surface": "#1a1c1f",
        "inverse-surface": "#2f3034",
        "inverse-primary": "#a9c8fd",
        "on-secondary-container": "#5e6367",
        "on-surface-variant": "#43474f",
        "error": "#ba1a1a",
        "ink-black": "#0F172A",
        "deep-navy": "#193B68",
        "surface-container-low": "#f4f3f7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "120px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "stack-md": "16px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "headline-sm": ["Source Serif 4", "serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Source Serif 4", "serif"],
        "display-lg": ["Source Serif 4", "serif"],
        "display-lg-mobile": ["Source Serif 4", "serif"],
        "stats-number": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "stats-number": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "300" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;